{{- if .Values.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ph-ee-connector-airtel
  annotations:
    {{- with .Values.serviceAccountAnnotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  labels:
    app: ph-ee-connector-airtel
  {{- end -}}